/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  available?: boolean;
  currentRole?: string;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type Fact = {
  _type: "fact";
  label: string;
  value: string;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  prose?: string;
  hobbies?: string;
  facts?: Array<
    {
      _key: string;
    } & Fact
  >;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  year: string;
  role: string;
  summary: string;
  heroImage: ImageWithAlt;
  overview?: string;
  detailImage?: ImageWithAlt;
  problem?: string;
  approach?: string;
  outcome?: string;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  stack?: Array<string>;
  url?: string;
  repo?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Settings
  | Link
  | Fact
  | About
  | Project
  | SanityImageAssetReference
  | ImageWithAlt
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/_components/about/about-section.tsx
// Variable: CURRENT_ROLE_QUERY
// Query: *[_type == "settings"][0] {  available,  currentRole}
export type CURRENT_ROLE_QUERY_RESULT = {
  available: boolean | null;
  currentRole: string | null;
} | null;

// Source: app/_components/about/about-section.tsx
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0] {  prose,  hobbies,  "facts": facts[] {    label,    value  },  "links": links[] {    label,    href,  },  "images": images[] {    "image": image.asset->url,    alt  }}
export type ABOUT_QUERY_RESULT = {
  prose: string | null;
  hobbies: string | null;
  facts: Array<{
    label: string;
    value: string;
  }> | null;
  links: Array<{
    label: string;
    href: string;
  }> | null;
  images: Array<{
    image: string | null;
    alt: string | null;
  }> | null;
} | null;

// Source: app/_components/hero/hero-section/hero-section.tsx
// Variable: AVAILABILITY_QUERY
// Query: *[_type == "settings"][0] {  available}
export type AVAILABILITY_QUERY_RESULT = {
  available: boolean | null;
} | null;

// Source: app/_components/work/work-section.tsx
// Variable: SELECTED_PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc) {    title,    "slug": slug.current,    year,    summary,    stack,    heroImage {      "image": image.asset->url,      alt    },  }
export type SELECTED_PROJECTS_QUERY_RESULT = Array<{
  title: string;
  slug: string;
  year: string;
  summary: string;
  stack: Array<string> | null;
  heroImage: {
    image: string | null;
    alt: string | null;
  };
}>;

// Source: app/work/[slug]/page.tsx
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    title,    year,    role,    stack,    summary,    heroImage {      "image": image.asset->url,      alt    },    overview,    detailImage {      "image": image.asset->url,      alt    },    problem,    approach,    outcome,    gallery,    url,    repo,  }
export type PROJECT_QUERY_RESULT = {
  title: string;
  year: string;
  role: string;
  stack: Array<string> | null;
  summary: string;
  heroImage: {
    image: string | null;
    alt: string | null;
  };
  overview: string | null;
  detailImage: {
    image: string | null;
    alt: string | null;
  } | null;
  problem: string | null;
  approach: string | null;
  outcome: string | null;
  gallery: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  url: string | null;
  repo: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n*[_type == "settings"][0] {\n  available,\n  currentRole\n}\n': CURRENT_ROLE_QUERY_RESULT;
    '\n*[_type == "about"][0] {\n  prose,\n  hobbies,\n  "facts": facts[] {\n    label,\n    value\n  },\n  "links": links[] {\n    label,\n    href,\n  },\n  "images": images[] {\n    "image": image.asset->url,\n    alt\n  }\n}\n': ABOUT_QUERY_RESULT;
    '\n*[_type == "settings"][0] {\n  available\n}\n': AVAILABILITY_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc) {\n    title,\n    "slug": slug.current,\n    year,\n    summary,\n    stack,\n    heroImage {\n      "image": image.asset->url,\n      alt\n    },\n  }\n': SELECTED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    title,\n    year,\n    role,\n    stack,\n    summary,\n    heroImage {\n      "image": image.asset->url,\n      alt\n    },\n    overview,\n    detailImage {\n      "image": image.asset->url,\n      alt\n    },\n    problem,\n    approach,\n    outcome,\n    gallery,\n    url,\n    repo,\n  }\n': PROJECT_QUERY_RESULT;
  }
}
