import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Cormorant } from "next/font/google";
import "lenis/dist/lenis.css";
import "./globals.css";

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300","400","500","600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} h-full antialiased cursor-none`}
    >
      <body className="min-h-full flex flex-col bg-">
          {children}
      </body>
    </html>
  );
}
