import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Cormorant, Geist } from "next/font/google";
import "lenis/dist/lenis.css";
import "./globals.css";
import { Navbar } from "@/components/navigation/navbar";

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});
const geist = Geist({
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${geist.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col items-center">
        <Navbar />
        <div className="container flex flex-col gap-24 px-5 md:px-0">
          {children}
        </div>
      </body>
    </html>
  );
}
